### ISSUE TITLE
There should only be one package.json file per project

### ISSUE THREAD

**Issue by LucianBuzzo** [amdomanska/currcalc-react#1]
Currently there are two package files, one for the client and one for the server.
Ideally there should just be one for this project.

**Comment by amdomanska** [comment]
However at the beginning it looked quite straightforward (just manually merge dependencies and scripts from these two files with necessary little adjustment to new folder structure) though it is not so easy because client part of the project was generated with create-react-app boilerplate (https://github.com/facebook/create-react-app). It generates build with scripts from react-script node module. It looks like to merge those two package.json files I would need to edit code of that module directly. It would require a lot of work that I aimed to avoid by using create-react-app ;) Especially that, to be honest, it seems quite reasonable to me to have two separate package.json files for client and server (for example: in the future I could pass frontend to someone else - it would be much easier to work separately on those if package.json files are separate).
